models:
  classifier : models/stage_1_rf_classifier_pipeline.pkl
  regressor : models/stage_2_rf_regression_pipeline.pkl


ui:
  default_inputs:
    no_of_dependents : 1
    education : Graduate
    self_employed : No 
    income_annum : 1200000
    loan_amount : 30000
    loan_term : 12 
    cibil_score : 800 
    residential_assets_value : 2000000
    commercial_assets_value : 2000000 
    luxury_assets_value : 0 
    bank_asset_value : 55000